{
  "$schema" = "https://opencode.ai/theme.json";
  defs = {
    dark_bg_main = "#1F1F1F";
    dark_bg_panel = "#181818";
    dark_bg_element = "#2A2D2E";
    dark_border_base = "#2B2B2B";
    dark_border_subtle = "#454545";
    dark_text_main = "#CCCCCC";
    dark_text_muted = "#9D9D9D";
    dark_primary_blue = "#0078D4";
    dark_secondary_purple = "#DA70D6";
    dark_accent_gold = "#FFD700";
    dark_success_green = "#2EA043";
    dark_error_red = "#F85149";
    dark_warning_yellow = "#CCA700";
    dark_info_blue = "#4DAAFC";
    dark_line_number = "#6E7681";
    dark_diff_add_bg = "#26413C";
    dark_diff_remove_bg = "#4A2927";
    dark_syntax_comment = "#6A9955";
    dark_syntax_keyword = "#C586C0";
    dark_syntax_function = "#DCDCAA";
    dark_syntax_variable = "#9CDCFE";
    dark_syntax_string = "#CE9178";
    dark_syntax_number = "#B5CEA8";
    dark_syntax_type = "#4EC9B0";
    dark_syntax_operator = "#D4D4D4";
    dark_syntax_punctuation = "#CCCCCC";
    dark_heading_blue = "#569CD6";
    dark_added_soft = "#81B88B";
    dark_removed_soft = "#C74E39";

    light_bg_main = "#F8F8F8";
    light_bg_panel = "#FFFFFF";
    light_bg_element = "#EEF0F4";
    light_border_base = "#D4D4D4";
    light_border_subtle = "#E5E7EB";
    light_text_main = "#3B3B3B";
    light_text_muted = "#6B6B6B";
    light_primary_blue = "#005FB8";
    light_secondary_purple = "#BC05BC";
    light_accent_gold = "#949800";
    light_success_green = "#107C10";
    light_error_red = "#CD3131";
    light_warning_yellow = "#949800";
    light_info_blue = "#0451A5";
    light_line_number = "#8A8A8A";
    light_diff_add_bg = "#E6F4EA";
    light_diff_remove_bg = "#FDECEC";
    light_syntax_comment = "#008000";
    light_syntax_keyword = "#0000FF";
    light_syntax_function = "#795E26";
    light_syntax_variable = "#001080";
    light_syntax_string = "#A31515";
    light_syntax_number = "#098658";
    light_syntax_type = "#267F99";
    light_syntax_operator = "#000000";
    light_syntax_punctuation = "#3B3B3B";
    light_heading_blue = "#0451A5";
    light_added_soft = "#107C10";
    light_removed_soft = "#CD3131";
  };
  theme = {
    primary = { dark = "dark_primary_blue"; light = "light_primary_blue"; };
    secondary = { dark = "dark_secondary_purple"; light = "light_secondary_purple"; };
    accent = { dark = "dark_accent_gold"; light = "light_accent_gold"; };
    error = { dark = "dark_error_red"; light = "light_error_red"; };
    warning = { dark = "dark_warning_yellow"; light = "light_warning_yellow"; };
    success = { dark = "dark_success_green"; light = "light_success_green"; };
    info = { dark = "dark_info_blue"; light = "light_info_blue"; };
    text = { dark = "dark_text_main"; light = "light_text_main"; };
    textMuted = { dark = "dark_text_muted"; light = "light_text_muted"; };
    background = { dark = "dark_bg_main"; light = "light_bg_main"; };
    backgroundPanel = { dark = "dark_bg_panel"; light = "light_bg_panel"; };
    backgroundElement = { dark = "dark_bg_element"; light = "light_bg_element"; };
    border = { dark = "dark_border_base"; light = "light_border_base"; };
    borderActive = { dark = "dark_primary_blue"; light = "light_primary_blue"; };
    borderSubtle = { dark = "dark_border_subtle"; light = "light_border_subtle"; };
    diffAdded = { dark = "dark_success_green"; light = "light_success_green"; };
    diffRemoved = { dark = "dark_error_red"; light = "light_error_red"; };
    diffContext = { dark = "dark_text_muted"; light = "light_text_muted"; };
    diffHunkHeader = { dark = "dark_line_number"; light = "light_line_number"; };
    diffHighlightAdded = { dark = "dark_added_soft"; light = "light_added_soft"; };
    diffHighlightRemoved = { dark = "dark_removed_soft"; light = "light_removed_soft"; };
    diffAddedBg = { dark = "dark_diff_add_bg"; light = "light_diff_add_bg"; };
    diffRemovedBg = { dark = "dark_diff_remove_bg"; light = "light_diff_remove_bg"; };
    diffContextBg = { dark = "dark_bg_panel"; light = "light_bg_panel"; };
    diffLineNumber = { dark = "dark_line_number"; light = "light_line_number"; };
    diffAddedLineNumberBg = { dark = "dark_diff_add_bg"; light = "light_diff_add_bg"; };
    diffRemovedLineNumberBg = { dark = "dark_diff_remove_bg"; light = "light_diff_remove_bg"; };
    markdownText = { dark = "dark_text_main"; light = "light_text_main"; };
    markdownHeading = { dark = "dark_heading_blue"; light = "light_heading_blue"; };
    markdownLink = { dark = "dark_info_blue"; light = "light_info_blue"; };
    markdownLinkText = { dark = "dark_syntax_variable"; light = "light_syntax_variable"; };
    markdownCode = { dark = "dark_syntax_string"; light = "light_syntax_string"; };
    markdownBlockQuote = { dark = "dark_syntax_comment"; light = "light_syntax_comment"; };
    markdownEmph = { dark = "dark_syntax_keyword"; light = "light_syntax_keyword"; };
    markdownStrong = { dark = "dark_syntax_function"; light = "light_syntax_function"; };
    markdownHorizontalRule = { dark = "dark_border_base"; light = "light_border_base"; };
    markdownListItem = { dark = "dark_heading_blue"; light = "light_heading_blue"; };
    markdownListEnumeration = { dark = "dark_syntax_type"; light = "light_syntax_type"; };
    markdownImage = { dark = "dark_info_blue"; light = "light_info_blue"; };
    markdownImageText = { dark = "dark_syntax_variable"; light = "light_syntax_variable"; };
    markdownCodeBlock = { dark = "dark_text_main"; light = "light_text_main"; };
    syntaxComment = { dark = "dark_syntax_comment"; light = "light_syntax_comment"; };
    syntaxKeyword = { dark = "dark_syntax_keyword"; light = "light_syntax_keyword"; };
    syntaxFunction = { dark = "dark_syntax_function"; light = "light_syntax_function"; };
    syntaxVariable = { dark = "dark_syntax_variable"; light = "light_syntax_variable"; };
    syntaxString = { dark = "dark_syntax_string"; light = "light_syntax_string"; };
    syntaxNumber = { dark = "dark_syntax_number"; light = "light_syntax_number"; };
    syntaxType = { dark = "dark_syntax_type"; light = "light_syntax_type"; };
    syntaxOperator = { dark = "dark_syntax_operator"; light = "light_syntax_operator"; };
    syntaxPunctuation = { dark = "dark_syntax_punctuation"; light = "light_syntax_punctuation"; };
  };
}
