import { map, rule } from "karabiner.ts";

export const fromQwertyToColemak = [
  rule("qwerty to colemak dhk").manipulators([
    map("q").to("q"),
    map("w").to("w"),
    map("c").to("c"),
    map("v").to("d"),
    map("e").to("f"),
    map("m").to("h"),
    map("l").to("i"),
    map("y").to("j"),
    map("h").to("k"),
    map("u").to("l"),
    map("n").to("m"),
    map("j").to("n"),
    map(";").to("o"),
    map("r").to("p"),
    map("s").to("r"),
    map("d").to("s"),
    map("f").to("t"),
    map("i").to("u"),
    map("x").to("x"),
    map("o").to("y"),
    map("z").to("z"),
    map("p").to(";"),
    map("b").to("v"),
    map("t").to("b"),
    map("k").to("e"),
  ]),
  rule("qwerty to colemak dhk with shift").manipulators([
    map("q", "shift").to("q", ["shift"]),
    map("w", "shift").to("w", ["shift"]),
    map("c", "shift").to("c", ["shift"]),
    map("v", "shift").to("d", ["shift"]),
    map("e", "shift").to("f", ["shift"]),
    map("m", "shift").to("h", ["shift"]),
    map("l", "shift").to("i", ["shift"]),
    map("y", "shift").to("j", ["shift"]),
    map("h", "shift").to("k", ["shift"]),
    map("u", "shift").to("l", ["shift"]),
    map("n", "shift").to("m", ["shift"]),
    map("j", "shift").to("n", ["shift"]),
    map(";", "shift").to("o", ["shift"]),
    map("r", "shift").to("p", ["shift"]),
    map("s", "shift").to("r", ["shift"]),
    map("d", "shift").to("s", ["shift"]),
    map("f", "shift").to("t", ["shift"]),
    map("i", "shift").to("u", ["shift"]),
    map("x", "shift").to("x", ["shift"]),
    map("o", "shift").to("y", ["shift"]),
    map("z", "shift").to("z", ["shift"]),
    map("p", "shift").to(";", ["shift"]),
    map("b", "shift").to("v", ["shift"]),
    map("t", "shift").to("b", ["shift"]),
    map("k", "shift").to("e", ["shift"]),
  ]),
];
