{
	"data": "ENC[AES256_GCM,data:QfwIDZRT6d0rymIIX9Rm+3ZG9zApeYQ3YCPgFpeq9xQCc5bxTrJ1jW2yRNqhmMELdBwpdWsZXmDXZswGqrzSwj0lWWi8VFyWA5Kk2NNJUjBh8zXTKpiF1zkxIfM=,iv:tlBwWJOKm4hMy3FZRa/XmbeuExvGbXj+HN7wrIE8qHM=,tag:v019xXWFy7E4ZJxpnpqYSw==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUnFNcStId2dkdUxPUkxl\nMGpyYUdOY0ZWbFNtU2l0K2hva3h4VWJDTGtJCkR4UTVtdkp2dXo1MzgrcU9zWUMv\nOXZNN1R5a3B4MDdjUnJLYXdIRERlRHMKLS0tIHgwQmZqNVYyR3pxZVh3VGZGZ3Vs\nY2RKK0JxUVVHOUtTTjh2U0habVFLaHMKzYe+3xiM1vw+eMPLf1RsP1OxnPxfDYTI\nL0kXRhzeSVA85GxdXUyeC/Xy0IIVWJ4vD1C8b09RSyfp0mHbaNbvvA==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age12cjyzl2r5mnt0k2w6t6zfurjmhrmlsn04txydhukj3vxd6tf2ccsapm8h4"
			}
		],
		"lastmodified": "2026-07-02T11:00:44Z",
		"mac": "ENC[AES256_GCM,data:I5ZGTh8pREMCUi9Rs/dqKqEiaacaXjJC2VFvY+04h8wD/n0LYt2s8Ex4I8BGo8U1J0c+z6jJgvuvx+D73qm0kC1jAzvVw0oPRFxbKJNPJ6jNUbi8bLGUyV89FtsMWQk8at9urxIhj6OVUf74Ve93sQ6h1ebx6YlW4W1T7KYWPDQ=,iv:hKA8sodazhP+RrRoUoYiq8mHWTwEApSOAoWcTRA8ZoA=,tag:FB2uLGaDT+UnD82czCyY+A==,type:str]",
		"version": "3.13.1"
	}
}
