dictionaries = ["en_us"]

words = [
  "anki",
  "astro",
  "browsermcp",
  "bunx",
  "cantarell",
  "clsx",
  "colemak",
  "dedupe",
  "deno",
  "fira",
  "ghostty",
  "glassdoor",
  "homebrew",
  "homerow",
  "hono",
  "hsl",
  "importmap",
  "karabiner",
  "linkedin",
  "llms",
  "lucide",
  "mastra",
  "mcp",
  "menlo",
  "npx",
  "ocr",
  "oklab",
  "oklch",
  "opencode",
  "openrouter",
  "overscan",
  "paneru",
  "preact",
  "prettierrc",
  "segoe",
  "singlefile",
  "sonner",
  "spacebar",
  "tanstack",
  "tolgee",
  "typesafety",
  "vitest",
  "workos",
  "youtuber",
  "zed",
  "zod",
  "zodvex",
]
